### ISSUE TITLE
stuck 1/3 running and updates not picked up

### ISSUE THREAD

**Issue by jrmurad** [tilt-dev/bazel_example#5]
When I run this example or my own bazel+nodejs code which I based off of it, I get stuck in this state. The services are actually running and responsive but the interface is reporting that they're not fully running. When I make a code change, "last edit" does update to reflect that something was detected but the service doesn't actually restart.

I tried with both microk8s and minikube. I also tried the code from the open PR with `--norun` but that resulted in an error about `skips_local_docker=True` and another error when I added that.

Finally, I tried Tilt's nodejs example and that worked fine... all services green and restarting upon code change.

![image](https://user-images.githubusercontent.com/172669/90346036-b8481480-dff3-11ea-8cd2-c90785196a2b.png)

**Comment by nicks** [comment]
Hi @jrmurad ! I just merged some updates to this repo and confirmed that it should all work now. Thanks for the report! Will re-open if you're still seeing an issue after the updates and we can dig in more.
